module.exports = {
    Hero: require('./Hero'),
    HomeSection: require('./HomeSection'),
    Customer: require('./Customer'),
    Certification: require('./Certification'),
    News: require('./News'),
    ContactInfo: require('./ContactInfo'),
    ContactSubmission: require('./ContactSubmission'),
    EmailConfig: require('./EmailConfig'),
    OverviewBanner: require('./OverviewBanner'),
    Milestone: require('./Milestone'),
    Message: require('./Message'),
    VisionMission: require('./VisionMission'),
    CoreValue: require('./CoreValue'),
    Facilities: require('./Facilities'),
    Automation: require('./Automation'),
    Machinery: require('./Machinery'),
    Products: require('./Products'),
    Careers: require('./Careers'),
    EcoFriendly: require('./EcoFriendly'),
    HomeContact: require('./HomeContact'),
    User: require('./User'),
  };